name: Build and test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: golang:1.22
    steps:
      - uses: actions/checkout@v2
      - name: Run coverage
        env:
          RMQ_HOST: rmq
        run: go test -race -coverpkg=./... -coverprofile=coverage.out -covermode=atomic ./...
      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true

